# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f375abbe007d9fd620521a5f3ec1d2b14f20e25ac4d5080423a3c7c57a2e1883a66744f935558b3e5891a6f4c81fd8451634bb89bc6fd797f83a399c119b99b1

test:
  secret_key_base: 79d10004480716f05eae9c34297121baf55ab21a24cfd4d781c27f5984b6b8ca87b731fbd38cdd72e5c192b1849a325fbd3595ed7b42764b8b9dd18a51231c74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
